language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
node_js:
  - "12"

before_install:
  - npm i -g npm

install:
  - npm ci

script:
- npm run format
- npm run lint
- if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then commitlint-travis; fi
- npm run test
- npm run bundlesize

# e2e ssr
- npm run build:ssr
- npm run e2e:ssr

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then npm run github-release; fi

addons:
  chrome: stable

env:
  global:
    secure: GywEi6rCdMo68c+2aSxF31yAtciDWgQ4A++zUXKXqFFlMRrzsSlgo0+US+eT/+Kaz5CZIXIKJiWRmbPdhgJKs1rkVE7CJiZokdDdgfoEy8xAmlMhjbYN44Y0j5S9bIlhwqR9kW9kNg2sj5/Kv88bjSXehmT+RdOFfGN5gkxTzhs=
